swagger: "2.0"  # Change 'openapi' to 'swagger' for OpenAPI 2.0
info:
  title: Mock Target API
  version: 1.0.0
  description: OpenAPI Specification for the Apigee mock target service endpoint.
host: mocktarget.apigee.net  # Add the 'host' field for OpenAPI 2.0 compatibility
basePath: /  # Add 'basePath' field for OpenAPI 2.0 compatibility
schemes:
  - http
  - https
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        "200":
          description: Success
