openapi: 3.0.0
info:
  title: Mock Target API
  version: 1.0.0
  description: OpenAPI Specification for the Apigee mock target service endpoint.
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        "200":
          description: Success
servers:
  - url: http://mocktarget.apigee.net
  - url: https://mocktarget.apigee.net
