name: Scheduled Apigee Proxy Calls

on:
  schedule:
    # Schedule to run every minute
    - cron: "*/1 * * * *"
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  call-apigee:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (if needed)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Call first Apigee Proxy
      - name: Call Apigee Proxy 1
        run: |
          curl -X GET "${{ vars.APIGEE_BASE_URL }}/west/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"

      # Call second Apigee Proxy
      - name: Call Apigee Proxy 2
        run: |
          curl -X GET "${{ vars.APIGEE_BASE_URL }}/es-test-contractawards/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"

      # Call third Apigee Proxy
      - name: Call Apigee Proxy 3
        run: |
          curl -X GET "${{ vars.APIGEE_BASE_URL }}/advana/sandbox/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"
