name: Simplified Apigee Proxy Calls

on:
  schedule:
    # Run every minute
    - cron: "* * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  call-apigee:
    runs-on: ubuntu-latest

    steps:
      # Call first Apigee Proxy
      - name: Call Apigee Proxy 1
        run: |
          curl -X GET "https://api.dev.advana.540.co/west/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"

      # Call second Apigee Proxy
      - name: Call Apigee Proxy 2
        run: |
          curl -X GET "https://api.dev.advana.540.co/es-test-contractawards/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"

      # Call third Apigee Proxy
      - name: Call Apigee Proxy 3
        run: |
          curl -X GET "https://api.dev.advana.540.co/advana/sandbox/v1/status-refresh" \
          -H "apikey: ${{ secrets.APIGEE_API_KEY }}" \
          -H "Content-Type: application/json"
